// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SqlUIClient is the client API for SqlUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SqlUIClient interface {
	// ListEngineSpecs returns a list of SQL Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SqlUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type sqlUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlUIClient(cc grpc.ClientConnInterface) SqlUIClient {
	return &sqlUIClient{cc}
}

func (c *sqlUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SqlUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SqlUI_ServiceDesc.Streams[0], "/v1.SqlUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sqlUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SqlUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type sqlUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *sqlUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sqlUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SqlUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlUIServer is the server API for SqlUI service.
// All implementations must embed UnimplementedSqlUIServer
// for forward compatibility
type SqlUIServer interface {
	// ListEngineSpecs returns a list of SQL Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, SqlUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSqlUIServer()
}

// UnimplementedSqlUIServer must be embedded to have forward compatible implementations.
type UnimplementedSqlUIServer struct {
}

func (UnimplementedSqlUIServer) ListEngineSpecs(*ListEngineSpecsRequest, SqlUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedSqlUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSqlUIServer) mustEmbedUnimplementedSqlUIServer() {}

// UnsafeSqlUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlUIServer will
// result in compilation errors.
type UnsafeSqlUIServer interface {
	mustEmbedUnimplementedSqlUIServer()
}

func RegisterSqlUIServer(s grpc.ServiceRegistrar, srv SqlUIServer) {
	s.RegisterService(&SqlUI_ServiceDesc, srv)
}

func _SqlUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SqlUIServer).ListEngineSpecs(m, &sqlUIListEngineSpecsServer{stream})
}

type SqlUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type sqlUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *sqlUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SqlUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SqlUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqlUI_ServiceDesc is the grpc.ServiceDesc for SqlUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SqlUI",
	HandlerType: (*SqlUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SqlUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _SqlUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sql-ui.proto",
}
